---
- hosts: localhost
  roles:
    - ops-hosts  

- hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - {name: common, tags: common}

- hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - {name: deploy_haproxy, tags: deploy_haproxy}

- hosts: apps
  gather_facts: true
  become: true
  roles:
    - {name: deploy_tomcat, tags: deploy_tomcat}
    - {name: deploy_apache, tags: deploy_apache}

- hosts: appdbs
  become: true
  roles:
    - {name: geerlingguy.postgresql, tags: postgresql}
